### ISSUE TITLE
def of core interpretation

### ISSUE THREAD

**Issue by fabianneuhaus** [gruninger/Common-Logic#52]
(a) non-empty universe of discourse 
(b) the range of funI  is total functions from UD_I* into UD_I
(c) ArcC(E)  are all discourse names

**Comment by fabianneuhaus** [comment]
this won't work after all

**Comment by whitten** [comment]
So to create a core interpretation of a Common Logic theory,
what else do you need beyond  the three you mentioned?

Btw, I assume UD_I is the Universe of Discourse of the Interpretation?
I don't know the abbreviation ArcC and assume E is an element in 
the non-empty universe of  discourse?

fabianneuhaus syggested that:
>Def of core interpretation
> (a) non-empty universe of discourse 
> (b) the range of funI is total functions from UD_I* into UD_I
> (c) ArcC(E) are all discourse names
